# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration
client_id = "4b7f66c05c811e17cce41dbeadebfe88"
name = "course-new-app"
handle = "course-new-app"
application_url = "https://course-both-combine.onrender.com"
embedded = true
[build]
automatically_update_urls_on_dev = true
[webhooks]
api_version = "2025-04"
[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_customers,write_customers,read_orders,write_orders,read_products"
[auth]
redirect_urls = ["https://course-both-combine.onrender.com/auth/callback", "https://course-both-combine.onrender.com/auth/shopify/callback", "https://course-both-combine.onrender.com/api/auth/callback"]
[pos]
embedded = false
[app_proxy]
url = "https://course-both-combine.onrender.com/api"
subpath = "courses"
prefix = "apps"
