# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "f39b6878f5c50c11b6b1ac02f4ab7ceb"
name = "net-course"
application_url = "https://fossil-hart-teaches-numeric.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_customers,write_orders,write_products"

[auth]
redirect_urls = [
  "https://fossil-hart-teaches-numeric.trycloudflare.com/auth/callback",
  "https://fossil-hart-teaches-numeric.trycloudflare.com/auth/shopify/callback",
  "https://fossil-hart-teaches-numeric.trycloudflare.com/api/auth/callback"
]
