api_version = "2025-04"

[[extensions]]
name = "custmer-latest"
handle = "custmer-latest"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/OrderStatusBlock.jsx"
target = "customer-account.order-index.block.render"


[extensions.capabilities]
api_access = true
network_access = false

[capabilities]
network_access = false
block_progress = false
